name: Build Geode Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: win
          - name: Android
            os: ubuntu-latest
            target: android64

    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: ${{ matrix.config.target }}
          sdk: latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VisualTPS-${{ matrix.config.name }}
          path: ${{ steps.build.outputs.build-output }}
